version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-matriculas
    restart: always
    environment:
      POSTGRES_DB: matriculasdb
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend-matriculas
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://meu_usuario:minha_senha@postgres:5432/matriculasdb
      PORT: 5000
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend-matriculas
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
