version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-matriculas
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-matriculasdb}
      POSTGRES_USER: ${POSTGRES_USER:-meu_usuario}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-minha_senha}
    networks:
      - matriculas-net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend-matriculas
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-meu_usuario}:${POSTGRES_PASSWORD:-minha_senha}@postgres:5432/${POSTGRES_DB:-matriculasdb}
      PORT: 5000
      ADMIN_USERNAME: ${ADMIN_USERNAME:-}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
      BLOCK_LOG_FILE: /app/blocked.log
    networks:
      - matriculas-net
    ports:
      - "5000:5000"
    volumes:
      - ./blocked.log:/app/blocked.log

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000/matriculas}
    container_name: frontend-matriculas
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5000/matriculas}
    networks:
      - matriculas-net
    ports:
      - "3000:3000"

volumes:
  postgres_data:

networks:
  matriculas-net:
